### ISSUE TITLE
can m3u.php support QUALITY SETTINGS ?

### ISSUE THREAD

**Issue by philboycn** [SxtBox/YouTube_CL_AIO_APIS#1]
i`m using xteve(with ffmpeg) on plex to stream u2b live streams on my devices, it need m3u8 format. older version that created on January 19 2020 was worked fine for me, it can choose quality use 95 as 720p or 96 as 1080p. but new version cannot choose quality, so ffmpeg said "invalid data found when processing input". pls help me out. Thank You !!

**Comment by SxtBox** [comment]
`is disabled in demo mode to get direct stream, only some functions are active, api is for sale.`
![Screenshot_ 2021-01-12 _ 11-42-24](https://user-images.githubusercontent.com/60861585/104304969-620cce00-54cc-11eb-8a9f-af6514601b13.png)

**Comment by philboycn** [comment]
> `is disabled in demo mode to get direct stream, only some functions are active, api is for sale.`
> ![Screenshot_ 2021-01-12 _ 11-42-24](https://user-images.githubusercontent.com/60861585/104304969-620cce00-54cc-11eb-8a9f-af6514601b13.png)

oh where i can buy this ?

**Comment by SxtBox** [comment]
use contact form by email in my infos.
